"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var react_1 = require("react");
var Footer = function () {
    (0, react_1.useEffect)(function () {
    }, []);
    return (React.createElement("footer", { className: "ftco-footer ftco-bg-dark ftco-section" },
        React.createElement("div", { className: "container" },
            React.createElement("div", { className: "row mb-5" },
                React.createElement("div", { className: "col-md" },
                    React.createElement("div", { className: "ftco-footer-widget mb-5" },
                        React.createElement("h2", { className: "ftco-heading-2 logo" },
                            "Easy",
                            React.createElement("span", null, "English")),
                        React.createElement("p", null, "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.")),
                    React.createElement("div", { className: "ftco-footer-widget mb-5" },
                        React.createElement("h2", { className: "ftco-heading-2" }, "Have a Questions?"),
                        React.createElement("div", { className: "block-23 mb-3" },
                            React.createElement("ul", null,
                                React.createElement("li", null,
                                    React.createElement("span", { className: "icon icon-map-marker" }),
                                    React.createElement("span", { className: "text" }, "203 Fake St. Mountain View, San Francisco, California, USA")),
                                React.createElement("li", null,
                                    React.createElement("a", { href: "#" },
                                        React.createElement("span", { className: "icon icon-phone" }),
                                        React.createElement("span", { className: "text" }, "+2 392 3929 210"))),
                                React.createElement("li", null,
                                    React.createElement("a", { href: "#" },
                                        React.createElement("span", { className: "icon icon-envelope" }),
                                        React.createElement("span", { className: "text" }, "info@yourdomain.com"))))),
                        React.createElement("ul", { className: "ftco-footer-social list-unstyled float-md-left float-lft mt-3" },
                            React.createElement("li", { className: "ftco-animate" },
                                React.createElement("a", { href: "#" },
                                    React.createElement("span", { className: "icon-twitter" }))),
                            React.createElement("li", { className: "ftco-animate" },
                                React.createElement("a", { href: "#" },
                                    React.createElement("span", { className: "icon-facebook" }))),
                            React.createElement("li", { className: "ftco-animate" },
                                React.createElement("a", { href: "#" },
                                    React.createElement("span", { className: "icon-instagram" })))))),
                React.createElement("div", { className: "col-md" },
                    React.createElement("div", { className: "ftco-footer-widget mb-5 ml-md-4" },
                        React.createElement("h2", { className: "ftco-heading-2" }, "Links"),
                        React.createElement("ul", { className: "list-unstyled" },
                            React.createElement("li", null,
                                React.createElement("a", { href: "#" },
                                    React.createElement("span", { className: "ion-ios-arrow-round-forward mr-2" }),
                                    "Home")),
                            React.createElement("li", null,
                                React.createElement("a", { href: "#" },
                                    React.createElement("span", { className: "ion-ios-arrow-round-forward mr-2" }),
                                    "About")),
                            React.createElement("li", null,
                                React.createElement("a", { href: "#" },
                                    React.createElement("span", { className: "ion-ios-arrow-round-forward mr-2" }),
                                    "Services")),
                            React.createElement("li", null,
                                React.createElement("a", { href: "#" },
                                    React.createElement("span", { className: "ion-ios-arrow-round-forward mr-2" }),
                                    "Deparments")),
                            React.createElement("li", null,
                                React.createElement("a", { href: "#" },
                                    React.createElement("span", { className: "ion-ios-arrow-round-forward mr-2" }),
                                    "Contact")))),
                    React.createElement("div", { className: "ftco-footer-widget mb-5 ml-md-4" },
                        React.createElement("h2", { className: "ftco-heading-2" }, "Services"),
                        React.createElement("ul", { className: "list-unstyled" },
                            React.createElement("li", null,
                                React.createElement("a", { href: "#" },
                                    React.createElement("span", { className: "ion-ios-arrow-round-forward mr-2" }),
                                    "Neurolgy")),
                            React.createElement("li", null,
                                React.createElement("a", { href: "#" },
                                    React.createElement("span", { className: "ion-ios-arrow-round-forward mr-2" }),
                                    "Dentist")),
                            React.createElement("li", null,
                                React.createElement("a", { href: "#" },
                                    React.createElement("span", { className: "ion-ios-arrow-round-forward mr-2" }),
                                    "Ophthalmology")),
                            React.createElement("li", null,
                                React.createElement("a", { href: "#" },
                                    React.createElement("span", { className: "ion-ios-arrow-round-forward mr-2" }),
                                    "Cardiology")),
                            React.createElement("li", null,
                                React.createElement("a", { href: "#" },
                                    React.createElement("span", { className: "ion-ios-arrow-round-forward mr-2" }),
                                    "Surgery"))))),
                React.createElement("div", { className: "col-md" },
                    React.createElement("div", { className: "ftco-footer-widget mb-5" },
                        React.createElement("h2", { className: "ftco-heading-2" }, "Recent Blog"),
                        React.createElement("div", { className: "block-21 mb-4 d-flex" },
                            React.createElement("a", { className: "blog-img mr-4", style: { backgroundImage: 'url(images/image_1.jpg)' } }),
                            React.createElement("div", { className: "text" },
                                React.createElement("h3", { className: "heading" },
                                    React.createElement("a", { href: "#" }, "Even the all-powerful Pointing has no control about")),
                                React.createElement("div", { className: "meta" },
                                    React.createElement("div", null,
                                        React.createElement("a", { href: "#" },
                                            React.createElement("span", { className: "icon-calendar" }),
                                            " Dec 25, 2018")),
                                    React.createElement("div", null,
                                        React.createElement("a", { href: "#" },
                                            React.createElement("span", { className: "icon-person" }),
                                            " Admin")),
                                    React.createElement("div", null,
                                        React.createElement("a", { href: "#" },
                                            React.createElement("span", { className: "icon-chat" }),
                                            " 19"))))),
                        React.createElement("div", { className: "block-21 mb-5 d-flex" },
                            React.createElement("a", { className: "blog-img mr-4", style: { backgroundImage: 'url(images/image_2.jpg)' } }),
                            React.createElement("div", { className: "text" },
                                React.createElement("h3", { className: "heading" },
                                    React.createElement("a", { href: "#" }, "Even the all-powerful Pointing has no control about")),
                                React.createElement("div", { className: "meta" },
                                    React.createElement("div", null,
                                        React.createElement("a", { href: "#" },
                                            React.createElement("span", { className: "icon-calendar" }),
                                            " Dec 25, 2018")),
                                    React.createElement("div", null,
                                        React.createElement("a", { href: "#" },
                                            React.createElement("span", { className: "icon-person" }),
                                            " Admin")),
                                    React.createElement("div", null,
                                        React.createElement("a", { href: "#" },
                                            React.createElement("span", { className: "icon-chat" }),
                                            " 19"))))))),
                React.createElement("div", { className: "col-md" },
                    React.createElement("div", { className: "ftco-footer-widget mb-5" },
                        React.createElement("h2", { className: "ftco-heading-2" }, "Opening Hours"),
                        React.createElement("h3", { className: "open-hours pl-4" },
                            React.createElement("span", { className: "ion-ios-time mr-3" }),
                            "We are open 24/7")),
                    React.createElement("div", { className: "ftco-footer-widget mb-5" },
                        React.createElement("h2", { className: "ftco-heading-2" }, "Subscribe Us!"),
                        React.createElement("form", { action: "#", className: "subscribe-form" },
                            React.createElement("div", { className: "form-group" },
                                React.createElement("input", { type: "text", className: "form-control mb-2 text-center", placeholder: "Enter email address" }),
                                React.createElement("input", { type: "submit", defaultValue: "Subscribe", className: "form-control submit px-3" })))))),
            React.createElement("div", { className: "row" },
                React.createElement("div", { className: "col-md-12 text-center" },
                    React.createElement("p", null,
                        "Copyright \u00A9 All rights reserved | This template is made with ",
                        React.createElement("i", { className: "icon-heart", "aria-hidden": "true" }),
                        " by ",
                        React.createElement("a", { href: "https://colorlib.com", target: "_blank" }, "Colorlib")))))));
};
exports.default = Footer;
//# sourceMappingURL=Footer.js.map